config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/cases/:id', to: 'cases#show', as: "case"
  get 'pages/components', to: 'pages#components'
  post 'cases/:id/leads', to: 'leads#create', as: "compute_result"
  patch 'leads/:id', to: 'leads#update', as: "lead"

  namespace :admin do
    resources :cases, only: [:index, :new, :create, :destroy, :show] do
      resources :leads, only: [:index]
      resources :variables, only: [:create]
      resources :lines, only: [:create, :update, :destroy]
      member do
        patch 'saveinputbuilder', as: "save_input"
        patch 'saveoutputbuilder', as: "save_output"
        patch 'outputpreferences', as: "save_outputpreferences"
        patch 'savevariables', as: "save_variables"
        patch 'testdata', as: "save_testdata"
        patch 'updatestatus', as: "update_case_status"

      end
    end
    get 'profile', to: 'users#profile'
    # get 'cases/:id/leads', to: 'leads#index'
    # post 'cases/:id/variables', to: 'variables#create'
    # post 'cases/:id/lines', to: 'lines#create', as: 'line_create'
    # patch 'cases/:id/line/:id', to: 'lines#update', as: 'line_update'
    # delete 'cases/:id/line/:id', to: 'lines#destroy', as: 'line_delete'
    # get 'cases', to: 'cases#index'
    # post 'cases', to: 'cases#create'
    # delete 'cases/:id', to: 'cases#delete'
    # get 'cases/:id', to: 'cases#show', as: :case
    # post 'cases/:id/saveinputbuilder', to: 'cases#saveinputbuilder', as: "save_input"
    # patch 'cases/:id/saveoutputbuilder', to: 'cases#saveoutputbuilder'
    # patch 'cases/:id/outputpreferences', to: 'cases#outputpreferences'
    # post 'cases/:id/testdata', to: 'cases#testdata'
    # patch 'cases/:id/updatestatus', to: 'cases#updatestatus'

  end
end

app/controllers/admin/cases_controller.rb
class Admin::CasesController < ApplicationController
  def index
    @cases = current_user.cases
    @case = Case.new
    @light_sidebar  = true
  end

  def new
    @case = Case.new
  end

  def create
    @case = Case.new(case_params)
    @case.status = "Unpublished"
    @case.user = current_user
    if @case.save
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def delete
  end

  def show
     @case = Case.find(params[:id])
     @line = Line.new
     @chart_globals = prep_chart_globals
     charts = prep_chart(@case)
     @expvariables = @case.variables.where(category: "expert", state: true)
     @chartM = charts[:chartM]
     @chartA = charts[:chartA]
     @chartB = charts[:chartB]
  end

  def saveinputbuilder
    @case = Case.find(params[:id])
    @case.update(case_params_input)
    update_input_variables(@case)
    @expvariables = @case.variables.where(category: "expert", state: true)
    respond_to do |format|
      format.js
    end
  end

  def saveoutputbuilder
    @case = Case.find(params[:id])
    @case.update(case_params_output)
  end

  def outputpreferences
  end

  def testdata
    @case = Case.find(params[:id])
    case_params_testdata(@case).each do |varname,expertval|
      unless expertval.blank?
        changevar = Variable.where(case_id: params[:id], category: "input", name: varname)
        changevar.update(expert_value: expertval.to_f)
      end

    @line = Line.new
    @chart_globals = prep_chart_globals
    charts = prep_chart(@case)
    @expvariables = @case.variables.where(category: "expert", state: true)
    @chartM = charts[:chartM]
    @chartA = charts[:chartA]
    @chartB = charts[:chartB]
    end
    respond_to do |format|
      format.js
    end
  end

  def updatestatus
    @case = Case.find(params[:id])
    @case.update(status: "Published")
  end

  def savevariables
    @case = Case.find(params[:id])
    vars = JSON.parse(case_params_variables[:variablesjson])
    newexpertvars = vars.select { |num,val|  val[0] != "@" }.keys
    oldexpertvars = Variable.where(case_id: params[:id], category: "expert").map(&:name)
    add = newexpertvars - oldexpertvars
    add.each do |a|
      Variable.create(name: a, expression: vars[a], category: "expert", case_id: @case.id, state: true)
    end
    disablevars = oldexpertvars - newexpertvars
    # disablevars.each do |disvar|
    #   Variable.where(case_id: @case.id, category: "expert", name: disvar).update_all(state: false)
    # end
    respond_to do |format|
      format.js
    end
  end


  private

  def prep_chart(mycase)
    mydata = mycase.build
    chartM = LazyHighCharts::HighChart.new('graph1') do |f|

      f.xAxis(categories: mydata[:xaxis])
      f.series(name: mycase.scenario_a, yAxis: 0, data: mydata[:Atotalc])
      f.series(name: mycase.scenario_b, yAxis: 0, data: mydata[:Btotalc])
      f.yAxis [
        {title: {text: "EUR", margin: 0} }
      ]

      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "line", backgroundColor: '#F4F4F4'})
    end
    chartA = LazyHighCharts::HighChart.new('graph2') do |f|

      f.xAxis(categories: mydata[:xaxis])
      mmin = [mydata[:Atotal].min, mydata[:Btotal].min].min - 5
      mmax = [mydata[:Atotal].max, mydata[:Btotal].max].max + 5

      mydata[:A].each do |graphlabel, graphdata|
        f.series(name: graphlabel, yAxis: 0, data: graphdata)
      end

      f.yAxis [
        {title: {text: "EUR", margin: 0}, min: mmin , max: mmax  }
      ]
      f.plotOptions(column: { stacking: 'normal'})
      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "column", height: '250', backgroundColor: '#F4F4F4'})
    end
    chartB = LazyHighCharts::HighChart.new('graph3') do |f|

      f.xAxis(categories: mydata[:xaxis])
      mmin = [mydata[:Atotal].min, mydata[:Btotal].min].min.round - 5
      mmax = [mydata[:Atotal].max, mydata[:Btotal].max].max.round + 5


      mydata[:B].each do |graphlabel, graphdata|
        f.series(name: graphlabel, yAxis: 0, data: graphdata)
      end

      f.yAxis [
        {title: {text: "EUR", margin: 0}, min: mmin , max: mmax }
      ]
      f.plotOptions(column: { stacking: 'normal'})
      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "column", height: '250', backgroundColor: '#F4F4F4'})
    end
    return {chartM: chartM ,chartA: chartA ,chartB: chartB}
  end

  def prep_chart_globals
    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, "rgb(244, 244, 244)"],
            [1, "rgb(244, 244, 244)"]
          ]
        },
      )
      f.lang(thousandsSep: ",")
      f.colors(["#3a506b", "#5bc0be", "#CCCCCC", "#f15c80", "#e4d354"])
    end
  end


  def case_params
     params.require(:case).permit(:user_input_text, :name, :scenario_a, :scenario_b)
  end

  def case_params_input
     params.require(:case).permit(:user_input_text)
  end

  def case_params_output
     parameters = {}
     parameters.merge!(params.require(:case).permit(:user_output_text))
     parameters.merge!(params.permit(:output_pref_1, :output_pref_2, :output_pref_3, :output_pref_4, :output_pref_5, :output_pref_6))
     parameters["output_pref_1"] ||= false
     parameters["output_pref_2"] ||= false
     parameters["output_pref_3"] ||= false
     parameters["output_pref_4"] ||= false
     parameters["output_pref_5"] ||= false
     parameters["output_pref_6"] ||= false
     return parameters
  end

  def case_params_variables
     params.permit(:variablesjson)
  end

  def case_params_testdata(mycase)
     list_params_allowed = mycase.variables.where(case_id: params[:id], category: "input").map(&:expression)
     params.permit(list_params_allowed)
  end

  def update_input_variables(mycase)
    regex = /(?:@[a-zA-Z]+)/
    newvars = mycase.user_input_text.scan(regex)
    oldvars = mycase.variables.where(category: "input").map(&:expression)
    add = newvars - oldvars
    disab = oldvars - newvars
    add.length > 0 ? addvariables(add, mycase) : nil
    disab.length > 0 ? disablevariables(delete, mycase) : nil
  end

  def addvariables(addarr, mycase)
    addarr.each do |add|
      Variable.create(name: add, expression: add, category: "input", case_id: mycase.id, state: true)
    end
  end

  def disablevariables(delarr, mycase)
    delarr.each do |del|
      mycase.variables.where(category: "input", expression: del).update(state: false)
    end
  end

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  layout "user_case", only: [:show] #render user_case layout instead of application



  def show
    @case = Case.find(params[:id])
    unless @case.status == "Published"
      flash[:notice] = "This case has not been published"
      redirect_to root_path
      return
    end

      @lead = Lead.create(case: @case)

      @out = {output_pref_1: 999, output_pref_2: 999, output_pref_3: 999, output_pref_4: 999, output_pref_5: 999, output_pref_6: 999 }
      charts = prep_chart(@case)
      @chartM = charts[:chartM]
      @chart_globals = prep_chart_globals


      @input = @case.user_input_text
  end



private

  def prep_chart(mycase, lead = nil)
    mydata = mycase.build(lead)
    chartM = LazyHighCharts::HighChart.new('graph1') do |f|
      f.title(text: mycase.name)
      f.xAxis(categories: mydata[:xaxis])
      f.series(name: mycase.scenario_a, yAxis: 0, data: mydata[:Atotalc])
      f.series(name: mycase.scenario_b, yAxis: 0, data: mydata[:Btotalc])
      f.yAxis [
        {title: {text: "EUR", margin: 0} }
      ]

      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "line", backgroundColor: '#F4F4F4'})
    end


    return {chartM: chartM}
  end


  def prep_chart_globals

    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, "rgb(244, 244, 244)"],
            [1, "rgb(244, 244, 244)"]
          ]
        },
      )
      f.lang(thousandsSep: ",")
      f.colors(["#3a506b", "#5bc0be", "#8085e9", "#f15c80", "#e4d354"])
    end
  end

end

app/views/cases/_user-case-form.html.erb
<div id="user-case-form-hidder">
  <%= simple_form_for lead, url: lead_path(lead), method: :patch, :remote => true, html: {class: 'form-inline', autocomplete: 'off' } do |f| %>
    <%= f.input :first_name, label: false, placeholder: ' First name', required: false %>
    <%= f.input :last_name, label: false, placeholder: ' Family name', required: false  %>
    <%= f.input :email, label: false, placeholder: ' Email' %>
    <%= f.button :submit, "SUBMIT", class: 'btn-CTA user-button margin-left border-none' %>
  <% end %>


</div>

app/views/cases/_user-results.html.erb
<div class="output-sentence">

<%= @output_sentence %>
   <!-- get a translation table from @outputpref to names of vars -->
   <!-- replace the name in out hash w correct name to match the string -->
   <!-- replace the output string with var names with output string w values _ values can be rounddown -->

</div>

<div>
  <%= high_chart_globals(@chart_globals) %>
  <%= high_chart("CaseChart", @chartM) %>
</div>

<div id="user-case-form-container">
   <h3 class="page-title color-white">That looks good! Enter your information below to discuss with us about it?</h3>

</div>

app/views/cases/show.html.erb
<div id="user-case-wrapper">


  <div  class="final-form-head" id="card">
    <div class="front">

     <!--  <h1>Welcome on Briefcase forms</h1> -->
      <h3>Invest or not in a product ? We tell you if its worth it.</h3>

      <%= simple_form_for @case, url: compute_result_path(@case), :html => {:id => "save-user-fill", autocomplete: 'off' } ,method: :post, remote: true do |f|%>
      <%= f.input :user_input_text, as: :text, label: false, wrapper: false, placeholder: "Example: I have @TotalUserBulbs incandencent lightbulbs with a wattage of UserBulbWattage ... ", input_html: { id:"filling"} %>
      <input type="hidden" name="lead_id" value="<%= @lead.id %>">

      <div class="around" id="input_second">
        <h3 class= page-title>Please fill in the form if you want to check our product value.</h3>
        <div id="preview" class="set-height">
          <div class="input-field" id="input-form"></div>
        </div>
      </div>

      <div class="save-button">
      <%= f.submit "SEE RESULT", :id => "turn-card", :class => "btn btn-CTA user-button" %>
      </div>
      <% end %>
    </div>

    <div class="back final-form-tow" id='results'>

    </div>
  </div>







</div>

<% content_for :after_js do %>
    <script src="https://cdn.rawgit.com/nnattawat/flip/master/dist/jquery.flip.min.js"></script>

    <script>
    $( document ).ready(function(){

      var emptyField = function() {

      var input = $('#filling').val();
      var regex = /(?:@[a-zA-Z]+)/g;
      var matches_array = input.match(regex);
      var input_empty_fields = input
      //var input_empty_fields = input.replace(regex, '<input type="text" name="amount"/>');

      matches_array.forEach(function(match) {
        input_empty_fields = input_empty_fields.replace(match, '<input type="text" type="number" name="vars['+match+']"/>')
      });

      $('.input-field').html(input_empty_fields);
      };

      $('#filling').hide()
          emptyField()

      $("#card").flip({
        trigger: 'manual',
        reverse: true,
        speed: 1000
      });

     $('#turn-card').on("click", function(){
      // $("#card").flip(true);

    $("#card").flip('toggle');

    });
    });
</script>
<% end %>