config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/cases/:id', to: 'cases#show', as: "case"
  get 'pages/components', to: 'pages#components'
  post 'cases/:id/leads', to: 'leads#create', as: "compute_result"
  patch 'leads/:id', to: 'leads#update', as: "lead"

  namespace :admin do
    resources :cases, only: [:index, :new, :create, :destroy, :show] do
      resources :leads, only: [:index]
      resources :variables, only: [:create]
      resources :lines, only: [:create, :update, :destroy]
      member do
        patch 'saveinputbuilder', as: "save_input"
        patch 'saveoutputbuilder', as: "save_output"
        patch 'outputpreferences', as: "save_outputpreferences"
        patch 'savevariables', as: "save_variables"
        patch 'testdata', as: "save_testdata"
        patch 'updatestatus', as: "update_case_status"

      end
    end
    get 'profile', to: 'users#profile'
    # get 'cases/:id/leads', to: 'leads#index'
    # post 'cases/:id/variables', to: 'variables#create'
    # post 'cases/:id/lines', to: 'lines#create', as: 'line_create'
    # patch 'cases/:id/line/:id', to: 'lines#update', as: 'line_update'
    # delete 'cases/:id/line/:id', to: 'lines#destroy', as: 'line_delete'
    # get 'cases', to: 'cases#index'
    # post 'cases', to: 'cases#create'
    # delete 'cases/:id', to: 'cases#delete'
    # get 'cases/:id', to: 'cases#show', as: :case
    # post 'cases/:id/saveinputbuilder', to: 'cases#saveinputbuilder', as: "save_input"
    # patch 'cases/:id/saveoutputbuilder', to: 'cases#saveoutputbuilder'
    # patch 'cases/:id/outputpreferences', to: 'cases#outputpreferences'
    # post 'cases/:id/testdata', to: 'cases#testdata'
    # patch 'cases/:id/updatestatus', to: 'cases#updatestatus'

  end
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :variable
  belongs_to :case

  validates :name, presence: true, uniqueness: { scope: :case_id,
    message: "Variable names should be unique within a single case" }
  validates :variable_id, presence: true
  validates :case_id, presence: true
  validates :scenario, presence: true
  validates :category, presence: true, inclusion: { in: ["cost", "revenue"] }
  validates :recurrence, presence: true, inclusion: { in: ["oneoff", "monthly", "quarterly", "yearly"] }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :escalator, presence: true

  def default_values
    self.escalator ||= 0 # note self.status = 'P' if self.status.nil? might be safer (per @frontendbeauty)
  end

  def build(extents, lead = nil)
    # Initialize this line to its own extents
    lineext = self.recurrence == "oneoff" ? 1 : (self.end_date.year * 12 + self.end_date.month) - (self.start_date.year * 12 + self.start_date.month)
    myline = Array.new(lineext, 0)
    # Load line characteristics
    category = self.category == "cost" ? -1 : 1
    arr = ["oneoff", "monthly", "quarterly", "yearly"]
    recurrence = [9999.0,1.0,3.0,12.0][arr.size.times.select {|i| arr[i] == self.recurrence}.first]
    reccadj = [9999.0,12.0,4.0,1.0][arr.size.times.select {|i| arr[i] == self.recurrence}.first]
    effectiveesc = ((1.0 + (self.escalator/100.0))**(1.0/reccadj))-1.0
    variable_value = self.variable.eval_var(lead) * category

    # Fill line
    idx = 0
    while idx <= lineext-1
      myline[idx] = variable_value
      variable_value *= (1 + effectiveesc)
      idx += recurrence
    end

    payload = Array.new(extents[:months], 0)
    offset = (self.start_date.year * 12 + self.start_date.month) - (extents[:absstart].year * 12 + extents[:absstart].month)
    payload[offset,lineext] = myline
    return {self.name.to_sym => payload}
  end

end

app/controllers/admin/line_controller.rb
class Admin::LineController < ApplicationController
  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/admin/lines_controller.rb
class Admin::LinesController < ApplicationController
  def create
    @case = Case.find(params[:case_id])
    @line = Line.new(line_params)
    @line.case = @case
    bool_new = @line.save
    if bool_new
      charts = prep_chart(@case)
      @chartM = charts[:chartM]
      @chartA = charts[:chartA]
      @chartB = charts[:chartB]
      @chart_globals = prep_chart_globals
    end
    if bool_new
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def update
    @case = Case.find(params[:case_id])
    @line = Line.find(params[:id])
    bool_upd = @line.update(line_params)
    if bool_upd
      charts = prep_chart(@case)
      @chartM = charts[:chartM]
      @chartA = charts[:chartA]
      @chartB = charts[:chartB]
      @chart_globals = prep_chart_globals
    end
    if bool_upd
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'cases/show' }
        format.js
      end
    end
  end

  def destroy
    @case = Case.find(params[:case_id])
    @line = Line.find(params[:id])
    @line_id = @line.id
    bool_dest = @line.destroy
    if bool_dest
      charts = prep_chart(@case)
      @chartM = charts[:chartM]
      @chartA = charts[:chartA]
      @chartB = charts[:chartB]
      @chart_globals = prep_chart_globals
    end
    if @line.destroy
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def reloadnewform
    @case = Case.find(params[:case_id])
    respond_to do |format|
      format.js
    end
  end

  private

  def prep_chart(mycase)
    mydata = mycase.build
    chartM = LazyHighCharts::HighChart.new('graph1') do |f|

      f.xAxis(categories: mydata[:xaxis])
      f.series(name: mycase.scenario_a, yAxis: 0, data: mydata[:Atotalc])
      f.series(name: mycase.scenario_b, yAxis: 0, data: mydata[:Btotalc])
      f.yAxis [
        {title: {text: "EUR", margin: 0} }
      ]

      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "line", backgroundColor: '#F4F4F4'})
    end
    chartA = LazyHighCharts::HighChart.new('graph2') do |f|

      f.xAxis(categories: mydata[:xaxis])
      mmin = [mydata[:Atotal].min, mydata[:Btotal].min].min - 10
      mmax = [mydata[:Atotal].max, mydata[:Btotal].max].max + 10

      mydata[:A].each do |graphlabel, graphdata|
        f.series(name: graphlabel, yAxis: 0, data: graphdata)
      end

      f.yAxis [
        {title: {text: "EUR", margin: 0}, min: mmin , max: mmax  }
      ]
      f.plotOptions(column: { stacking: 'normal'})
      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "column", height: '250', backgroundColor: '#F4F4F4'})
    end
    chartB = LazyHighCharts::HighChart.new('graph3') do |f|

      f.xAxis(categories: mydata[:xaxis])
      mmin = [mydata[:Atotal].min, mydata[:Btotal].min].min.round - 10
      mmax = [mydata[:Atotal].max, mydata[:Btotal].max].max.round + 10


      mydata[:B].each do |graphlabel, graphdata|
        f.series(name: graphlabel, yAxis: 0, data: graphdata)
      end

      f.yAxis [
        {title: {text: "EUR", margin: 0}, min: mmin , max: mmax }
      ]
      f.plotOptions(column: { stacking: 'normal'})
      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "column", height: '250', backgroundColor: '#F4F4F4'})
    end
    return {chartM: chartM ,chartA: chartA ,chartB: chartB}
  end

  def prep_chart_globals
    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, "rgb(244, 244, 244)"],
            [1, "rgb(244, 244, 244)"]
          ]
        },
      )
      f.lang(thousandsSep: ",")
      f.colors(["#3a506b", "#5bc0be", "#8085e9", "#f15c80", "#e4d354"])
    end
  end

  def line_params
    params.permit(:name, :variable_id, :scenario, :category, :recurrence, :start_date, :end_date, :escalator)
  end
end

app/views/admin/lines/_newjsline.html.erb
<%= form_tag(admin_line_update_path, method: 'post', remote: true ) do %>
  <div class="line-form">
    <div class="line-name">
      <div class="form-group">
        <input type="text" class="form-control" id="line-name"  name="name" placeholder="Name this line" value=<%= @line.name %>>
      </div>
    </div>

    <div class="line-scenario">
      <div class="form-check">
      <label class="form-check-label">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" <%= @line.scenario == "A" ? "checked" : nil %>>
        A
      </label>
      <label class="form-check-label">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2" <%= @line.scenario == "B" ? "checked" : nil %>>
        B
      </label>
      </div>
    </div>

    <div class="line-variable">
      <div class="form-group">
        <label class="sr-only" for="guest">Variable</label>
        <select id="guest" name="variable" class="form-control">
            <% @case.variables.where("category = ? OR category = ?", "input","expert").each do |variable| %>
             <option <%= @line.variable.name == variable.name ? "selected" : nil %> value=<%= variable.name %> ><%=variable.name%></option>
            <%end%>
        </select>
      </div>
    </div>

    <div class="line-category">
      <div class="form-group">
        <label class="sr-only" for="category">Category</label>
        <select id="category" name="category" class="form-control">
             <option <%= @line.category == "cost" ? "selected" : nil %> value="cost">Cost</option>
             <option <%= @line.category == "revenue" ? "selected" : nil %> value="revenue">Revenue</option>
        </select>
      </div>
    </div>

    <div class="line-reccurence">
      <div class="form-group">
        <label class="sr-only" for="recurrence">Reccurence</label>
        <select id="recurrence" name="recurrence" class="form-control" selected=<%= @line.recurrence %>>
             <option <%= @line.recurrence == "oneoff" ? "selected" : nil %> value="oneoff">One-off</option>
             <option <%= @line.recurrence == "monthly" ? "selected" : nil %> value="monthly">Monthly</option>
             <option <%= @line.recurrence == "quarterly" ? "selected" : nil %> value="quarterly">Quarterly</option>
             <option <%= @line.recurrence == "yearly" ? "selected" : nil %> value="yearly">Yearly</option>
        </select>
      </div>
    </div>

    <div class="line-startdate">
      <div class="form-group">
        <label class="sr-only" for="chkin">Start date</label>
        <div class="input-group">
          <input type="text" class="form-control chkin" id="chkin<%=@line.id%>" name="chkin" placeholder="Start date" value=<%= @line.end_date.strftime("%d/%m/%Y") %>>
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" id="glyph-chkin"></i></span>
        </div>
      </div>
    </div>

    <div class="line-enddate">
      <div class="form-group">
        <label class="sr-only" for="chkout">End date</label>
        <div class="input-group">
          <input type="text" class="form-control chkin" id="chkout<%=@line.id%>"  name="chkout" placeholder="End Date" value=<%= @line.end_date.strftime("%d/%m/%Y") %>>
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" id="glyph-chkout"></i></span>
        </div>
      </div>
    </div>

    <div class="line-escalator">
      <div class="form-group">
          <input class="form-control" type="number" value=<%= @line.escalator%> id="example-number-input" placeholder="Annual escalator">
      </div>
    </div>

    <div class="line-new">
      <%= button_tag type: 'submit', class: "fabutton", id: "register-button" do %>
        <i class="fa fa-floppy-o" aria-hidden="true"></i>
      <%end%>
      <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, admin_line_delete_path(@case, @line),
          data: {:confirm => 'Are you sure?'}, :method => :delete %>
    </div>


  </div>
<%end%>

app/views/admin/lines/create.html.erb
<h1>Admin::Line#create</h1>
<p>Find me in app/views/admin/line/create.html.erb</p>

app/views/admin/lines/create.js.erb
var new_line = $("<%= j render 'admin/cases/newjsline', case: @case, line: @line %>")
$('#existing-lines').append(new_line);
$('#existing-lines').html("<%= j render 'admin/cases/existinglines', case: @case, line: @line %>");
$('#new-line-s-form').html("<%= j render 'admin/cases/newformline', case: @case%>");
$('#bcgraphs').html("<%= j render 'admin/cases/bcgraphs', chartM: @chartM%>")
$('#Agraph').html("<%= j render 'admin/cases/SCNA_graph', chartA: @chartA%>")
$('#Bgraph').html("<%= j render 'admin/cases/SCNB_graph', chartB: @chartB%>")
reset_datepickers()

app/views/admin/lines/destroy.html.erb
<h1>Admin::Line#destroy</h1>
<p>Find me in app/views/admin/line/destroy.html.erb</p>

app/views/admin/lines/destroy.js.erb
$("#line-<%=@line_id%>").hide()
$('#bcgraphs').html("<%= j render 'admin/cases/bcgraphs', chartM: @chartM%>")
$('#Agraph').html("<%= j render 'admin/cases/SCNA_graph', chartA: @chartA%>")
$('#Bgraph').html("<%= j render 'admin/cases/SCNB_graph', chartB: @chartB%>")

app/views/admin/lines/update.html.erb
<h1>Admin::Line#update</h1>
<p>Find me in app/views/admin/line/update.html.erb</p>

app/views/admin/lines/update.js.erb
$('#bcgraphs').html("<%= j render 'admin/cases/bcgraphs', chartM: @chartM%>")
$('#Agraph').html("<%= j render 'admin/cases/SCNA_graph', chartA: @chartA%>")
$('#Bgraph').html("<%= j render 'admin/cases/SCNB_graph', chartB: @chartB%>")