config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/cases/:id', to: 'cases#show', as: "case"
  get 'pages/components', to: 'pages#components'
  post 'cases/:id/leads', to: 'leads#create', as: "compute_result"
  patch 'leads/:id', to: 'leads#update', as: "lead"

  namespace :admin do
    resources :cases, only: [:index, :new, :create, :destroy, :show] do
      resources :leads, only: [:index]
      resources :variables, only: [:create]
      resources :lines, only: [:create, :update, :destroy]
      member do
        patch 'saveinputbuilder', as: "save_input"
        patch 'saveoutputbuilder', as: "save_output"
        patch 'outputpreferences', as: "save_outputpreferences"
        patch 'savevariables', as: "save_variables"
        patch 'testdata', as: "save_testdata"
        patch 'updatestatus', as: "update_case_status"

      end
    end
    get 'profile', to: 'users#profile'
    # get 'cases/:id/leads', to: 'leads#index'
    # post 'cases/:id/variables', to: 'variables#create'
    # post 'cases/:id/lines', to: 'lines#create', as: 'line_create'
    # patch 'cases/:id/line/:id', to: 'lines#update', as: 'line_update'
    # delete 'cases/:id/line/:id', to: 'lines#destroy', as: 'line_delete'
    # get 'cases', to: 'cases#index'
    # post 'cases', to: 'cases#create'
    # delete 'cases/:id', to: 'cases#delete'
    # get 'cases/:id', to: 'cases#show', as: :case
    # post 'cases/:id/saveinputbuilder', to: 'cases#saveinputbuilder', as: "save_input"
    # patch 'cases/:id/saveoutputbuilder', to: 'cases#saveoutputbuilder'
    # patch 'cases/:id/outputpreferences', to: 'cases#outputpreferences'
    # post 'cases/:id/testdata', to: 'cases#testdata'
    # patch 'cases/:id/updatestatus', to: 'cases#updatestatus'

  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     <a href="#" class="alert-link">...</a>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#">Terms & Conditions</a>
    <a href="#">Privacy Policy</a>
    <a href="#">FAQ</a>
  </div>
</div>

app/views/shared/_navbar-loggedin.html.erb
<div class="navbar-in-shape">
<!-- to push the logo to the middle -->
    <div >
    </div>
     <!-- Logo -->
    <%= link_to root_path, class: "navbar-in-briefcases-brand" do %>
      <%= image_tag "logo_briefcases.png" %>
    <% end %>
<!-- Log out link -->
    <div class="setting">
      <div class="setting-circle">
        <div class="dropdown">
          <i class="fa fa-home dropdown-toggle padding" id="trigger" data-toggle="dropdown" aria-hidden="true"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to admin_profile_path do %>
                  <i class="fa fa-cog"></i> <%= t(".account", default: "My account") %>
                <% end %>
              </li>

              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: " Log-out") %>
                <% end %>
              </li>
            </ul>
          </div>

    <!-- AVATAR END -->

      </div>
    </div>
</div>

app/views/shared/_navbar-logout.html.erb
<div class="navbar-out-shape">

  <!-- Left Navigation -->
  <div class="navbar-out-briefcases-left hidden-xs hidden-sm">
    <%= link_to "Features", "#", class: "navbar-out-briefcases-item navbar-out-briefcases-link" %>
    <%= link_to "Pricing", "#", class: "navbar-out-briefcases-item navbar-out-briefcases-link" %>
    <%= link_to "About", "#", class: "navbar-out-briefcases-item navbar-out-briefcases-link" %>
  </div>

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-out-briefcases-brand" do %>
    <%= image_tag "logo_briefcases.png" %>
  <% end %>

  <!-- Registration -->
  <div class="navbar-out-briefcases-left hidden-xs hidden-sm">
    <div class="login">
      <%= link_to new_user_session_path, method: :get do %><i class="fa fa-user-circle" aria-hidden="true" "></i><% end %>
      <%= link_to "Log in",  new_user_session_path, method: :get, class: "navbar-out-briefcases-item navbar-out-briefcases-link space" %>
    </div>
    <%= link_to "Sign up", new_user_registration_path, method: :get, class: "btn-CTA" %>
  </div>
</div>







  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-out-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-out-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
      <%= link_to('/admin/profile') do %>
        <div class="sidebar-header">

  <!-- AVATAR -->
  <!-- PART DELETED HERE: Cloudinary photo -->
          <div class="persona" >
            <% if current_user.facebook_picture_url %>
              <%= image_tag current_user.facebook_picture_url, class: "avatar" %>
            <% else %>
              <%= image_tag 'user_profile_picture.png', class: "avatar" %>
            <% end %>

            <div class="user-name">
              <h4> <%= current_user.first_name %></h4>
            </div>
          </div>
        <!-- AVATAR END -->
        </div>
      <% end %>

        <div class="button-container">
          <ul class="list-unstyled">
             <li>
                <%= link_to "All Cases", admin_cases_path, class: "reverse-CTA" %>
              </li>
          </ul>
        </div>


        <ul class="list-unstyled components">
          <li id="start-point-1">
 <!--  -->
         <!--  <div href="#pageSubmenu" data-toggle="collapse" ></div> -->

<% unless @light_sidebar %>

              <%= link_to "Build Case", admin_case_path(@case), :id => "pageSubmenu-target" %>


                <ul class="collapse list-unstyled" id="pageSubmenu">

                    <li data-menuanchor="firstPage" class="active">
                      <a href="1">
                        <span>
                          <i data-menuanchor="firstPage" class="hidden-awsome active fa fa-dot-circle-o">&nbsp&nbsp</i>
                        </span>User Input Form
                      </a>
                    </li>
                    <li data-menuanchor="secondPage"><a href="#secondPage/2"><span><i data-menuanchor="secondPage" class="hidden-awsome fa fa-dot-circle-o">&nbsp&nbsp</i></span>  Output Message</a></li>
                    <li data-menuanchor="thirdPage"><a href="#thirdPage/3"><span><i data-menuanchor="thirdPage" class="hidden-awsome fa fa-dot-circle-o">&nbsp&nbsp</i></span>  Variables Definition</a></li>
                    <li data-menuanchor="fourthPage"><a href="#fourthPage/4"><span><i data-menuanchor="fourthPage" class="hidden-awsome fa fa-dot-circle-o">&nbsp&nbsp</i></span>  Test Data</a></li>
                    <li data-menuanchor="fifthPage"><a href="#fifthPage/5"><span><i data-menuanchor="fifthPage" class="hidden-awsome fa fa-dot-circle-o">&nbsp&nbsp</i></span>  Scenario Builder</a></li>
                    <li data-menuanchor="sixthPage"><a href="#sixthPage/6"><span><i data-menuanchor="sixthPage" class="hidden-awsome fa fa-dot-circle-o">&nbsp&nbsp</i></span>  Publish Case</a></li>
                </ul>
            </li>
            <li class="pointer" id="start-point-2">
                <a href="#">Manage</a>
            </li>
            <li class="pointer" id="start-point-3">
                <%= link_to "Leads", admin_case_leads_path(@case) %>
            </li>
            <li class="pointer" id="start-point-4">
                <a href="#">Analytics</a>
            </li>
            <li class="pointer" id="start-point-5">
                <a href="#">API</a>
            </li>

<% else %>
   </li>
<% end %>

        </ul>
    </nav>
</div>