config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/cases/:id', to: 'cases#show', as: "case"
  get 'pages/components', to: 'pages#components'
  post 'cases/:id/leads', to: 'leads#create', as: "compute_result"
  patch 'leads/:id', to: 'leads#update', as: "lead"

  namespace :admin do
    resources :cases, only: [:index, :new, :create, :destroy, :show] do
      resources :leads, only: [:index]
      resources :variables, only: [:create]
      resources :lines, only: [:create, :update, :destroy]
      member do
        patch 'saveinputbuilder', as: "save_input"
        patch 'saveoutputbuilder', as: "save_output"
        patch 'outputpreferences', as: "save_outputpreferences"
        patch 'savevariables', as: "save_variables"
        patch 'testdata', as: "save_testdata"
        patch 'updatestatus', as: "update_case_status"

      end
    end
    get 'profile', to: 'users#profile'
    # get 'cases/:id/leads', to: 'leads#index'
    # post 'cases/:id/variables', to: 'variables#create'
    # post 'cases/:id/lines', to: 'lines#create', as: 'line_create'
    # patch 'cases/:id/line/:id', to: 'lines#update', as: 'line_update'
    # delete 'cases/:id/line/:id', to: 'lines#destroy', as: 'line_delete'
    # get 'cases', to: 'cases#index'
    # post 'cases', to: 'cases#create'
    # delete 'cases/:id', to: 'cases#delete'
    # get 'cases/:id', to: 'cases#show', as: :case
    # post 'cases/:id/saveinputbuilder', to: 'cases#saveinputbuilder', as: "save_input"
    # patch 'cases/:id/saveoutputbuilder', to: 'cases#saveoutputbuilder'
    # patch 'cases/:id/outputpreferences', to: 'cases#outputpreferences'
    # post 'cases/:id/testdata', to: 'cases#testdata'
    # patch 'cases/:id/updatestatus', to: 'cases#updatestatus'

  end
end

app/controllers/admin/cases_controller.rb
class Admin::CasesController < ApplicationController
  def index
    @cases = current_user.cases
    @case = Case.new
    @light_sidebar  = true
  end

  def new
    @case = Case.new
  end

  def create
    @case = Case.new(case_params)
    @case.status = "Unpublished"
    @case.user = current_user
    if @case.save
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def delete
  end

  def show
     @case = Case.find(params[:id])
     @line = Line.new
     @chart_globals = prep_chart_globals
     charts = prep_chart(@case)
     @expvariables = @case.variables.where(category: "expert", state: true)
     @chartM = charts[:chartM]
     @chartA = charts[:chartA]
     @chartB = charts[:chartB]
  end

  def saveinputbuilder
    @case = Case.find(params[:id])
    @case.update(case_params_input)
    update_input_variables(@case)
    @expvariables = @case.variables.where(category: "expert", state: true)
    respond_to do |format|
      format.js
    end
  end

  def saveoutputbuilder
    @case = Case.find(params[:id])
    @case.update(case_params_output)
  end

  def outputpreferences
  end

  def testdata
    @case = Case.find(params[:id])
    case_params_testdata(@case).each do |varname,expertval|
      unless expertval.blank?
        changevar = Variable.where(case_id: params[:id], category: "input", name: varname)
        changevar.update(expert_value: expertval.to_f)
      end

    @line = Line.new
    @chart_globals = prep_chart_globals
    charts = prep_chart(@case)
    @expvariables = @case.variables.where(category: "expert", state: true)
    @chartM = charts[:chartM]
    @chartA = charts[:chartA]
    @chartB = charts[:chartB]
    end
    respond_to do |format|
      format.js
    end
  end

  def updatestatus
    @case = Case.find(params[:id])
    @case.update(status: "Published")
  end

  def savevariables
    @case = Case.find(params[:id])
    vars = JSON.parse(case_params_variables[:variablesjson])
    newexpertvars = vars.select { |num,val|  val[0] != "@" }.keys
    oldexpertvars = Variable.where(case_id: params[:id], category: "expert").map(&:name)
    add = newexpertvars - oldexpertvars
    add.each do |a|
      Variable.create(name: a, expression: vars[a], category: "expert", case_id: @case.id, state: true)
    end
    disablevars = oldexpertvars - newexpertvars
    # disablevars.each do |disvar|
    #   Variable.where(case_id: @case.id, category: "expert", name: disvar).update_all(state: false)
    # end
    respond_to do |format|
      format.js
    end
  end


  private

  def prep_chart(mycase)
    mydata = mycase.build
    chartM = LazyHighCharts::HighChart.new('graph1') do |f|

      f.xAxis(categories: mydata[:xaxis])
      f.series(name: mycase.scenario_a, yAxis: 0, data: mydata[:Atotalc])
      f.series(name: mycase.scenario_b, yAxis: 0, data: mydata[:Btotalc])
      f.yAxis [
        {title: {text: "EUR", margin: 0} }
      ]

      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "line", backgroundColor: '#F4F4F4'})
    end
    chartA = LazyHighCharts::HighChart.new('graph2') do |f|

      f.xAxis(categories: mydata[:xaxis])
      mmin = [mydata[:Atotal].min, mydata[:Btotal].min].min - 5
      mmax = [mydata[:Atotal].max, mydata[:Btotal].max].max + 5

      mydata[:A].each do |graphlabel, graphdata|
        f.series(name: graphlabel, yAxis: 0, data: graphdata)
      end

      f.yAxis [
        {title: {text: "EUR", margin: 0}, min: mmin , max: mmax  }
      ]
      f.plotOptions(column: { stacking: 'normal'})
      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "column", height: '250', backgroundColor: '#F4F4F4'})
    end
    chartB = LazyHighCharts::HighChart.new('graph3') do |f|

      f.xAxis(categories: mydata[:xaxis])
      mmin = [mydata[:Atotal].min, mydata[:Btotal].min].min.round - 5
      mmax = [mydata[:Atotal].max, mydata[:Btotal].max].max.round + 5


      mydata[:B].each do |graphlabel, graphdata|
        f.series(name: graphlabel, yAxis: 0, data: graphdata)
      end

      f.yAxis [
        {title: {text: "EUR", margin: 0}, min: mmin , max: mmax }
      ]
      f.plotOptions(column: { stacking: 'normal'})
      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "column", height: '250', backgroundColor: '#F4F4F4'})
    end
    return {chartM: chartM ,chartA: chartA ,chartB: chartB}
  end

  def prep_chart_globals
    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, "rgb(244, 244, 244)"],
            [1, "rgb(244, 244, 244)"]
          ]
        },
      )
      f.lang(thousandsSep: ",")
      f.colors(["#3a506b", "#5bc0be", "#CCCCCC", "#f15c80", "#e4d354"])
    end
  end


  def case_params
     params.require(:case).permit(:user_input_text, :name, :scenario_a, :scenario_b)
  end

  def case_params_input
     params.require(:case).permit(:user_input_text)
  end

  def case_params_output
     parameters = {}
     parameters.merge!(params.require(:case).permit(:user_output_text))
     parameters.merge!(params.permit(:output_pref_1, :output_pref_2, :output_pref_3, :output_pref_4, :output_pref_5, :output_pref_6))
     parameters["output_pref_1"] ||= false
     parameters["output_pref_2"] ||= false
     parameters["output_pref_3"] ||= false
     parameters["output_pref_4"] ||= false
     parameters["output_pref_5"] ||= false
     parameters["output_pref_6"] ||= false
     return parameters
  end

  def case_params_variables
     params.permit(:variablesjson)
  end

  def case_params_testdata(mycase)
     list_params_allowed = mycase.variables.where(case_id: params[:id], category: "input").map(&:expression)
     params.permit(list_params_allowed)
  end

  def update_input_variables(mycase)
    regex = /(?:@[a-zA-Z]+)/
    newvars = mycase.user_input_text.scan(regex)
    oldvars = mycase.variables.where(category: "input").map(&:expression)
    add = newvars - oldvars
    disab = oldvars - newvars
    add.length > 0 ? addvariables(add, mycase) : nil
    disab.length > 0 ? disablevariables(delete, mycase) : nil
  end

  def addvariables(addarr, mycase)
    addarr.each do |add|
      Variable.create(name: add, expression: add, category: "input", case_id: mycase.id, state: true)
    end
  end

  def disablevariables(delarr, mycase)
    delarr.each do |del|
      mycase.variables.where(category: "input", expression: del).update(state: false)
    end
  end

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  layout "user_case", only: [:show] #render user_case layout instead of application



  def show
    @case = Case.find(params[:id])
    unless @case.status == "Published"
      flash[:notice] = "This case has not been published"
      redirect_to root_path
      return
    end

      @lead = Lead.create(case: @case)

      @out = {output_pref_1: 999, output_pref_2: 999, output_pref_3: 999, output_pref_4: 999, output_pref_5: 999, output_pref_6: 999 }
      charts = prep_chart(@case)
      @chartM = charts[:chartM]
      @chart_globals = prep_chart_globals


      @input = @case.user_input_text
  end



private

  def prep_chart(mycase, lead = nil)
    mydata = mycase.build(lead)
    chartM = LazyHighCharts::HighChart.new('graph1') do |f|
      f.title(text: mycase.name)
      f.xAxis(categories: mydata[:xaxis])
      f.series(name: mycase.scenario_a, yAxis: 0, data: mydata[:Atotalc])
      f.series(name: mycase.scenario_b, yAxis: 0, data: mydata[:Btotalc])
      f.yAxis [
        {title: {text: "EUR", margin: 0} }
      ]

      f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
      f.chart({defaultSeriesType: "line", backgroundColor: '#F4F4F4'})
    end


    return {chartM: chartM}
  end


  def prep_chart_globals

    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, "rgb(244, 244, 244)"],
            [1, "rgb(244, 244, 244)"]
          ]
        },
      )
      f.lang(thousandsSep: ",")
      f.colors(["#3a506b", "#5bc0be", "#8085e9", "#f15c80", "#e4d354"])
    end
  end

end

app/views/admin/cases/_SCNA_graph.html.erb
<div id="Agraph">
  <%= high_chart_globals(@chart_globals) %>
  <%= high_chart("BC_SCN_A", @chartA) %>
</div>

app/views/admin/cases/_SCNB_graph.html.erb
<div id="Bgraph">
  <%= high_chart_globals(@chart_globals) %>
  <%= high_chart("BC_SCN_B", @chartB) %>
</div>

app/views/admin/cases/_bcgraphs.html.erb
<div id="bcgraphs">
  <%= high_chart_globals(@chart_globals) %>
  <%= high_chart("CaseChart", @chartM) %>
</div>

app/views/admin/cases/_newformline.html.erb
<div class="line-form">
<div><p>Name</p></div>
<div><p>Scenario</p></div>
<div><p>Variable</p></div>
<div><p>Category</p></div>
<div><p>Recurrence</p></div>
<div><p>Start Date</p></div>
<div><p>End Date</p></div>
<div><p>Escalator (%)</p></div>
<div><p></p></div>
</div>
<%= form_tag(admin_case_lines_path(@case), method: 'post', remote: true ) do %>
  <div class="line-form">
    <div class="line-name">
      <div class="form-group-margin form-group">
        <input type="text" class="form-control" id="line-name"  name="name" placeholder="Name this line">
      </div>
    </div>

    <div class="line-scenario line-item-centered">
      <div class="form-check">
      <label class="form-check-label">
        <input class="form-check-input" type="radio" name="scenario" id="exampleRadios1" value="A" checked>
        A
      </label>
      <label class="form-check-label">
        <input class="form-check-input" type="radio" name="scenario" id="exampleRadios2" value="B">
        B
      </label>
      </div>
    </div>

    <div class="line-variable">
      <div class="form-group-margin form-group">
        <label class="sr-only" for="guest">Variable</label>
        <select id="guest" name="variable_id" class="form-control">
            <% @case.variables.where("category = ? OR category = ?", "input","expert").where("state = ?", true).each do |variable| %>
             <option value='<%= variable.id %>' ><%=variable.name%></option>
            <%end%>
        </select>
      </div>
    </div>

    <div class="line-category">
      <div class="form-group-margin form-group">
        <label class="sr-only" for="category">Category</label>
        <select id="category" name="category" class="form-control">
             <option value="cost">Cost</option>
             <option value="revenue">Revenue</option>
        </select>
      </div>
    </div>

    <div class="line-reccurence">
      <div class="form-group-margin form-group">
        <label class="sr-only" for="recurrence">Reccurence</label>
        <select id="recurrence" name="recurrence" class="form-control">
             <option value="oneoff">One-off</option>
             <option value="monthly">Monthly</option>
             <option value="quarterly">Quarterly</option>
             <option value="yearly">Yearly</option>
        </select>
      </div>
    </div>

    <div class="line-startdate">
      <div class="form-group-margin form-group">
        <label class="sr-only" for="chkin">Start date</label>
        <div class="input-group">
          <input type="text" class="form-control chkin" id="newchkin" name="start_date" placeholder="Start date">
          <span class="input-group-addon glyph-chkin"><i class="glyphicon glyphicon-calendar" id="glyph-chkin"></i></span>
        </div>
      </div>
    </div>

    <div class="line-enddate">
      <div class="form-group-margin form-group">
        <label class="sr-only" for="chkout">End date</label>
        <div class="input-group">
          <input type="text" class="form-control chkout" id="newchkout"  name="end_date" placeholder="End Date">
          <span class="input-group-addon glyph-chkout"><i class="glyphicon glyphicon-calendar" id="glyph-chkout"></i></span>
        </div>
      </div>
    </div>

    <div class="line-escalator">
      <div class="form-group-margin form-group">
          <input class="form-control" type="number" step="0.001" id="example-number-input" placeholder="Annual escalator (%)" name="escalator">
      </div>
    </div>

    <div class="line-new line-item-centered">
      <%= button_tag type: 'submit', class: "fabutton cta-green", id: "register-button" do %>
        <i class="fa fa-2x fa-plus-circle" aria-hidden="true" style="color:rgba(91, 192, 190, 1)"></i>
        <% end %>
    </div>
  </div>
<%end%>

app/views/admin/cases/_newjsline.html.erb
<%= form_for @line, url: admin_case_line_path(@case, @line), method: 'post', remote: true do %>
  <div class="line-form">
    <div class="line-name">
      <div class="form-group">
        <input type="text" class="form-control" id="line-name"  name="name" placeholder="Name this line" value="<%= @line.name %>">
      </div>
    </div>

    <div class="line-scenario">
      <div class="form-check">
      <label class="form-check-label">
        <input class="form-check-input" type="radio" name="scenario" id="exampleRadios1" value="A" <%= @line.scenario == "A" ? "checked" : nil %>>
        A
      </label>
      <label class="form-check-label">
        <input class="form-check-input" type="radio" name="scenario" id="exampleRadios2" value="B" <%= @line.scenario == "B" ? "checked" : nil %>>
        B
      </label>
      </div>
    </div>

    <div class="line-variable">
      <div class="form-group">
        <label class="sr-only" for="guest">Variable</label>
        <select id="guest" name="variable" class="form-control">
            <% @case.variables.where("category = ? OR category = ?", "input","expert").where("state = ?", true).each do |variable| %>
             <option <%= @line.variable.name == variable.name ? "selected" : nil %> value="<%= variable.name %>" ><%=variable.name%></option>
            <%end%>
        </select>
      </div>
    </div>

    <div class="line-category">
      <div class="form-group">
        <label class="sr-only" for="category">Category</label>
        <select id="category" name="category" class="form-control">
             <option <%= @line.category == "cost" ? "selected" : nil %> value="cost">Cost</option>
             <option <%= @line.category == "revenue" ? "selected" : nil %> value="revenue">Revenue</option>
        </select>
      </div>
    </div>

    <div class="line-reccurence">
      <div class="form-group">
        <label class="sr-only" for="recurrence">Reccurence</label>
        <select id="recurrence" name="recurrence" class="form-control" selected=<%= @line.recurrence %>>
             <option <%= @line.recurrence == "oneoff" ? "selected" : nil %> value="oneoff">One-off</option>
             <option <%= @line.recurrence == "monthly" ? "selected" : nil %> value="monthly">Monthly</option>
             <option <%= @line.recurrence == "quarterly" ? "selected" : nil %> value="quarterly">Quarterly</option>
             <option <%= @line.recurrence == "yearly" ? "selected" : nil %> value="yearly">Yearly</option>
        </select>
      </div>
    </div>

    <div class="line-startdate">
      <div class="form-group">
        <label class="sr-only" for="chkin">Start date</label>
        <div class="input-group">
          <input type="text" class="form-control chkin" id="chkin<%=@line.id%>" name="chkin" placeholder="Start date" value=<%= @line.end_date.strftime("%d/%m/%Y") %>>
          <span class="input-group-addon glyph-chkin"><i class="glyphicon glyphicon-calendar" id="glyph-chkin"></i></span>
        </div>
      </div>
    </div>

    <div class="line-enddate">
      <div class="form-group">
        <label class="sr-only" for="chkout">End date</label>
        <div class="input-group">
          <input type="text" class="form-control chkout" id="chkout<%=@line.id%>"  name="chkout" placeholder="End Date" value=<%= @line.end_date.strftime("%d/%m/%Y") %>>
          <span class="input-group-addon glyph-chkout"><i class="glyphicon glyphicon-calendar" id="glyph-chkout"></i></span>
        </div>
      </div>
    </div>

    <div class="line-escalator">
      <div class="form-group">
          <input class="form-control" type="number" name="escalator" step="0.001" value='<%= @line.escalator%>' id="example-number-input" placeholder="Annual escalator (%)">
      </div>
    </div>

    <div class="line-new">
      <%= button_tag type: 'submit', class: "fabutton", id: "register-button" do %>
        <i class="fa fa-floppy-o" aria-hidden="true"></i>
      <%end%>
      <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, admin_case_line_path(@case, line),
            data: {:confirm => 'Are you sure?'}, :method => :delete %>
    </div>
  </div>
<%end%>

app/views/admin/cases/_publish.html.erb
<div class="around" id="publish_first">
  <h3 class= page-title>VIEW CASE AND PUBLISH</h3>
  <%= render "bcgraphs" %>
</div>
<div class="around" id="publish_second">
  <%= link_to case_url(@case) do %>
    <div class="btn btn-action btn-block preview-btn-margins"> PREVIEW </div>
  <% end %>

  <%= link_to update_case_status_admin_case_path(@case), :method=> :patch do %>
    <div class="btn btn-CTA btn-block preview-btn-margins"> PUBLISH </div>
  <% end %>

  <div id="bc_input">
    <i class="fa fa-link fa-2x" aria-hidden="true"></i>
    <input type="text" name="custom-link" value=<%= 'briefcases.io'+case_path(@case) %> id="link" class="active">
    <button id="bc_copy" data-clipboard-action="copy" data-clipboard-target="#link" class="copy-btn btn-action" style="display: inline-block;">COPY</button>
  </div>

</div>

app/views/admin/cases/_saveinputbuilder.html.erb
<div class="around" id="input_first">
  <h3 class= page-title>USER FORM BUILDER</h3>
  <div class="input-text-box">
    <%= simple_form_for @case, remote: true, url: save_input_admin_case_path(@case), :html => {:id => "save-input-form"} ,method: :patch do |f|%>
    <%= f.input :user_input_text, as: :text, label: false, wrapper: false, placeholder: "Example:\n I have @TotalBulbs lightbulbs with a wattage of @UserWattage wats ... ", input_html: { id:"hello"} %>
    <% end %>
  </div>
</div>

<div class="around" id="input_second">
  <h3 class= page-title>USER FORM PREVIEW</h3>
  <div id="preview">
    <div id="input-form" class="text-input">
    </div>
  </div>
</div>

<div class="around" id="input_third">
  <div class="Section-Header">
    <h3 class= page-title> USER INPUT FIELDS</h3>
    <div class="save-button">
      <%= button_tag type: 'submit', form: "save-input-form", class: "fabutton save-btn-inner", id: "global-save-1" do %>
      <i class="fa fa-floppy-o" aria-hidden="true"></i>
      <h4> CASE</h4><% end %>
    </div>
  </div>
  <div class="form-builder">
    <div id="input_var_container" class="container text-center">
      <ul id="variables-box">

      </ul>
    </div>
  </div>
</div>
<div class="" id="input_fourth">
  <div class="arrow-group">
    <div class="arrow-text">
      <h3>BUILD OUTPUT MESSAGE</h3>
    </div>
    <div class="arrow bounce" id="to-secondPage">
      <a class="fa fa-arrow-down fa-2x b-arrow" href="#secondPage"></a>
    </div>
  </div>
</div>


<% content_for :after_js do %>
  <script>

    window.expertVariables = <%= raw @expvariables.to_json %>;
    // Javascript to the input form page
    var print_text = function(div) {
      window.expertVariables = <%= raw @expvariables.to_json %>;
      // on every key up, we get value in form and put it in preview and replace "@word" with an empty input field.
      var sentence = div.val();
      var regex = /(?:@[a-zA-Z]+)/g;
      var matches_array = sentence.match(regex);
      var sentence_with_input = sentence

      if (sentence.match(regex) !== null) {
        matches_array.forEach(function(match) {
              sentence_with_input = sentence_with_input.replace(match, '<input type="text" type="number" name="'+match+'"/>')
          });
      }



      $('.text-input').html(sentence_with_input);

      // we check the string that start with @ and remove special characters after that string
      var variables = []
      // var regex = /(?:@[a-zA-Z]+)/g;
      var moto;

      do {
        moto = regex.exec(sentence);
        if (moto) {
          variables.push(moto[0]);
        }
      } while (moto);

      // we transform the array variables into an oject call obj
      function toObject(arr) {
        var rv = {};
        for (var i = 0; i < arr.length; ++i)
          rv[arr[i]] = arr[i];
        return rv;
      }
      obj = toObject(variables)

      // we store all the values of the keys of that object into the array syntax
      var syntax = Object.values(obj)

      // we append every of those value to our variables box
      $('#variables-box').html('');
      $('#shut').html('');

      syntax.forEach(function(s){
        $('#variables-box').append('<li class="variables-style">'  + s + '</li>');
        $('#shut').append('<li><a href="javascript:void(0);" class="formula-custom ui-draggable ui-draggable-handle" data-value="' + s + '">' + s +'</a></li>');
          //<a href="javascript:void(0);" class="formula-custom ui-draggable ui-draggable-handle" data-value="AMEER IS">TEXT AMEER</a>
      });
      variables_refresh()
       document.loadDraggables();
    };

    $( document ).ready(function() {

      // On keyup, we call the print_text() function.
      var $this = $("#hello")

      $this.keyup(function() {
        print_text($this)
      });


      // if we click on "Add variable", it adds an @ sign in our form field (better UX)
      $("#add").click(function(){
        var text = $("#hello")
        text.val(text.val() + '@');
        $("#hello").focus()
      });



    });

  </script>
<% end %>

app/views/admin/cases/create.js.erb
<% if @case.errors.any? %>
  // Render new_case form with errors
  $('#create-modal').html("<%= j render 'new_case' %>");
<% else %>
    window.location.href = "<%= admin_case_path(@case) %>";
<% end %>

app/views/admin/cases/index.html.erb
<div class="app-screen-index">
  <div class="wrapper-admin-cases-index">

    <div class="col-xs-12 row">


      <div class="col-xs-12 col-sm-6 col-md-4">

<!--  New case: calls the new.js.erb (instead of html.erb)   -->
          <%= link_to new_admin_case_path, remote: true, class: "card-case", id: "plus-card" do %>
              <div class="card-case-details">
                <h1>+</h1>
                <p>Create new case</p>
              </div>
          <% end %>
      </div>

        <% @cases.each do |one_case| %>

      <div class="col-xs-12 col-sm-6 col-md-4">
          <%= link_to admin_case_path(one_case) do %>

          <!--  one card  -->
          <div class="card-case">
            <div class="card-case-details">
              <h4><%= one_case.name %></h4>

              <% if one_case.status == "Published" %>
              <p style="color: green;"> <%= one_case.status %> </p>
              <% else %>
              <p style="color: orange;"> <%= one_case.status %> </p>
              <% end %>
            </div>

            <div class="card-case-info-wrapper">
              <div class="card-case-info">
                <div class="col-sm-12 card-case-info-element" id="first-scenario">
                  <p><%= one_case.scenario_a %>  </p>
                </div>
                <i class="fa fa-arrows-v"></i>
                <div class="col-sm-12 card-case-info-element" id="last-scenario">
                  <p> <%= one_case.scenario_b %> </p>
                </div>
              </div>
            </div>
          </div>

          <% end %>
          </div>
        <% end %>
      </div>


  </div>
</div>



<!-- MODAL -->
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">

</div>

app/views/admin/cases/saveinputbuilder.js.erb
$('#new-line-s-form').html("<%= j render 'admin/cases/newformline', case: @case%>");
$('#existing-lines').html("<%= j render 'admin/cases/existinglines', case: @case, line: @line %>");
window.expertVariables = <%= raw @expvariables.to_json %>;
reset_datepickers()

app/views/admin/cases/savevariables.js.erb
$('#new-line-s-form').html("<%= j render 'admin/cases/newformline', case: @case%>");
$('#existing-lines').html("<%= j render 'admin/cases/existinglines', case: @case, line: @line %>");
window.expertVariables = <%= raw @expvariables.to_json %>;
reset_datepickers()

app/views/admin/cases/testdata.html.erb
<h1>Admin::Cases#testdata</h1>
<p>Find me in app/views/admin/cases/testdata.html.erb</p>

app/views/admin/cases/testdata.js.erb
$('#existing-lines').html("<%= j render 'admin/cases/existinglines', case: @case, line: @line %>");
$('#new-line-s-form').html("<%= j render 'admin/cases/newformline', case: @case%>");
$('#bcgraphs').html("<%= j render 'admin/cases/bcgraphs', chartM: @chartM%>")
$('#Agraph').html("<%= j render 'admin/cases/SCNA_graph', chartA: @chartA%>")
$('#Bgraph').html("<%= j render 'admin/cases/SCNB_graph', chartB: @chartB%>")
reset_datepickers()